language: node_js
install:
  - npm install -g codecov
  - npm install
node_js:
  - "stable"
script:
  - npm run lint
  - npm run test-cov && codecov -f coverage/lcov.info
  - npm run release
cache: npm
dist: trusty
sudo: false
